/**
 * @file 统一 Electron IPC 总线全部共享导出。
 */

export { IPC_CHANNELS, IPC_EVENTS, IPC_PERMISSIONS, DEFAULT_IPC_MAX_PAYLOAD_BYTES, DEFAULT_IPC_TIMEOUT_MS } from './constants'
export { requestContracts, eventContracts, defineEventContract, defineRequestContract, createEmptyObjectSchema } from './contracts'
export { IPC_ERROR_CODES, createIpcError, createIpcErrorResult, createIpcSuccessResult, isIpcErrorCode } from './errors'
export {
  FILE_DIALOG_PROPERTIES,
  TASK_KINDS,
  TASK_START_STATUSES,
  appInfoResponseSchema,
  dbBackupResponseSchema,
  dbClearLogsResponseSchema,
  dbHealthResponseSchema,
  dbRestoreRequestSchema,
  dbRestoreResponseSchema,
  dbStatsResponseSchema,
  dbVacuumResponseSchema,
  fileDialogFilterSchema,
  fileDialogRequestSchema,
  fileDialogResponseSchema,
  getCurrentWindowResponseSchema,
  getInitPayloadResponseSchema,
  importPlanItemSchema,
  ipcErrorSchema,
  ipcResultSchema,
  openWindowRequestSchema,
  openWindowResponseSchema,
  setWindowTitleRequestSchema,
  settingGetRequestSchema,
  settingItemSchema,
  settingListRequestSchema,
  settingListResponseSchema,
  settingSetRequestSchema,
  taskCancelRequestSchema,
  taskCancelResponseSchema,
  taskCompletedEventSchema,
  taskDataByIdRequestSchema,
  taskDataCreateRequestSchema,
  taskDataItemSchema,
  taskDataListRequestSchema,
  taskDataListResponseSchema,
  taskDataUpdateRequestSchema,
  taskFailedEventSchema,
  taskProgressEventSchema,
  taskStartRequestSchema,
  taskStartResponseSchema,
  windowActionRequestSchema,
  windowActionResponseSchema,
  windowCloseByRoleRequestSchema,
  windowControlRequestSchema,
  windowControlResponseSchema,
  windowCountResponseSchema,
  windowCreatedEventSchema,
  windowFocusChangedEventSchema,
  windowListResponseSchema,
  windowRefSchema,
  windowRouteChangedEventSchema,
  windowSetTitleIpcRequestSchema,
  windowSetTitleResponseSchema,
  windowStateChangedEventSchema,
  xuanbingFileDialogRequestSchema,
  xuanbingFileDialogResponseSchema,
  xuanbingFileDryRunImportRequestSchema,
  xuanbingFileDryRunImportResponseSchema,
  xuanbingFileExportRequestSchema,
  xuanbingFileExportResponseSchema,
  xuanbingFileImportRequestSchema,
  xuanbingFileImportResponseSchema,
  xuanbingFilePreviewResponseSchema,
  xuanbingFileValidateResponseSchema,
  createIpcResultSchema
} from './schemas'
export type {
  OpenWindowRequestInput,
  OpenWindowResponseOutput,
  WindowControlRequestInput,
  WindowControlResponseOutput,
  WindowListResponseOutput,
  SetWindowTitleRequestInput,
  GetInitPayloadResponseOutput,
  GetCurrentWindowResponseOutput
} from './schemas'
export { SimpleZodSchema, ZodValidationError, z } from './zod'
export type {
  EventContract,
  EventContractMap,
  InferEventPayload,
  InferRequestInput,
  InferRequestOutput,
  InferSchema,
  IpcContractMetadata,
  IpcEventChannel,
  IpcEventDirection,
  IpcPermission,
  IpcRateLimit,
  IpcRequestChannel,
  RequestContract,
  RequestContractMap
} from './types'
export type {
  IpcError,
  IpcErrorCode,
  IpcFailureResult,
  IpcResult,
  IpcSuccessResult
} from './errors'

/* ───────────────────────── 数据库 shared 层 ───────────────────────── */

export {
  DB_ERROR_CODES,
  DbErrorException,
  createDbError,
  isDbErrorCode,
  throwDbError,
  DEFAULT_PAGE,
  MAX_PAGE_SIZE,
  computePageMeta,
  normalizePageQuery,
  pageQueryToOffsetLimit,
  AUDIT_ACTIONS,
  AUDIT_ACTOR_TYPES,
  FILE_ASSET_CATEGORIES,
  LOG_LEVELS,
  SETTING_VALUE_TYPES,
  SYNC_DIRECTIONS,
  SYNC_OPERATIONS,
  SYNC_STATUSES,
  TASK_EVENT_TYPES,
  TASK_STATUSES,
  TASK_TYPES,
  CURRENT_SCHEMA_VERSION,
  DB_DIR_NAMES,
  MAX_BACKUPS_TO_KEEP,
  MIGRATION_TABLE,
  SCHEMA_VERSION_TABLE,
  SQLITE_DB_FILENAME,
  XUANBING_CONFLICT_STRATEGIES,
  XUANBING_DOT_EXTENSION,
  XUANBING_EXTENSION,
  XUANBING_FILE_TYPES,
  XUANBING_FORMAT_VERSION,
  XUANBING_MAGIC,
  XUANBING_MAX_FILE_BYTES
} from './database'
export type {
  DbError,
  DbErrorCode,
  DbErrorSeverity,
  DbTimestamp,
  ListQuery,
  PageQuery,
  PageResult,
  SortDirection,
  SortParam,
  AuditAction,
  AuditActorType,
  BaseEntity,
  FileAssetCategory,
  LogLevel,
  SettingValueType,
  SoftDeletableEntity,
  SyncDirection,
  SyncOperation,
  SyncStatus,
  SyncableEntity,
  TaskEvent,
  TaskEventType,
  TaskStatus,
  TaskType,
  XuanbingConflictStrategy,
  XuanbingFileType
} from './database'
